### ISSUE TITLE
блок иф-елс

### ISSUE THREAD

**Issue by Rentalas** [BobkovValeriy/LopesJS#16]
https://github.com/BobkovValeriy/LopesJS/blob/8538524437f35478edbc3664666f6f2c2f774a78/js/basisJSpage.js#L39
в условном блоке проверяется что месседж это тру значение, соответственно можно написать просто if (message). 

https://github.com/BobkovValeriy/LopesJS/blob/8538524437f35478edbc3664666f6f2c2f774a78/js/basisJSpage.js#L52
то же самое

https://github.com/BobkovValeriy/LopesJS/blob/8538524437f35478edbc3664666f6f2c2f774a78/js/basisJSpage.js#L66
то же самое

**Comment by BobkovValeriy** [comment]
> I do
