### ISSUE TITLE
исправление 2

### ISSUE THREAD

**Issue by Rentalas** [BobkovValeriy/LopesJS#17]
https://github.com/BobkovValeriy/LopesJS/blob/8538524437f35478edbc3664666f6f2c2f774a78/js/basisJSpage.js#L41
не забываем ставить ';'

https://github.com/BobkovValeriy/LopesJS/blob/8538524437f35478edbc3664666f6f2c2f774a78/js/basisJSpage.js#L56
то же самое

https://github.com/BobkovValeriy/LopesJS/blob/8538524437f35478edbc3664666f6f2c2f774a78/js/basisJSpage.js#L90
https://github.com/BobkovValeriy/LopesJS/blob/8538524437f35478edbc3664666f6f2c2f774a78/js/basisJSpage.js#L91

**Comment by BobkovValeriy** [comment]
I do
