### ISSUE TITLE
Отделяем создание переменных от логики

### ISSUE THREAD

**Issue by Rentalas** [BobkovValeriy/LopesJS#20]
https://github.com/BobkovValeriy/LopesJS/blob/8538524437f35478edbc3664666f6f2c2f774a78/js/basisJSpage.js#L87-L91
Для лучшей читаемости кода пишем сначала переменные потом логику. 
В тех случаях когда у нас переменная не меняется - используем const вместо let.
Не забываем про ';'

**Comment by BobkovValeriy** [comment]
Ай ду)
