### ISSUE TITLE
Not completed homework

### ISSUE THREAD

**Issue by EskalonaD** [BobkovValeriy/LopesJS#3]
https://github.com/BobkovValeriy/LopesJS/blob/39774f56267966b91cf254d0194a7f9f5cb9ed3c/js/script.js#L139
There is no 1-3 tasks from https://learn.javascript.ru/operators#tasks
Please add them. You can simple left this code undisplayed if solution doesn't required it.

Also there is no solutions for https://learn.javascript.ru/comparison#tasks

**Comment by BobkovValeriy** [comment]
Done
